%\VignetteIndexEntry{NarrowPeaks Vignette I. Splitting and Narrowing Down ChIP-seq Peaks.}
%\VignetteDepends{}
%\VignetteKeywords{Visualization,ChIPseq,Transcription,Genetics,Sequencing,HighThroughputSequencing}
%\VignettePackage{NarrowPeaks}
\documentclass{article}

<<style, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex(use.unsrturl=FALSE)
@

\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{natbib}

\begin{document}

\bioctitle[An Introduction to the \Biocpkg{NarrowPeaks} Package]%
  {An Introduction to the \Biocpkg{NarrowPeaks} Package:\\ Narrowing Down Transcription Factor Binding Site Candidates from Functional Data}
\date{Created: January, 2013. Last modified: September, 2013. Compiled: \today}
\author{Pedro Madrigal}

\maketitle


\begin{small}
\begin{flushleft}
$^{1}$ Department of Biometry and Bioinformatics, Institute of Plant Genetics, Polish Academy of Sciences, Poznan, Poland \\
$^{2}$ \underline{Present address}: Wellcome Trust Sanger Institute, Hinxton, Cambridge, UK
\end{flushleft}
\end{small}


\tableofcontents


<<setup, echo=FALSE, results=hide>>=
options(width=100)
options(continue=" ")
options(prompt="R> ")
@ 

\section{Goal of this Vignette}
I will show how to meaningfully split and narrow down the lengths of ChIP-seq peaks in a WIG file by means of functional PCA. 

\section{Introduction}
Comprehensive ChIP-Seq data analyses are carried out by the coordinated interplay of several software tools \cite{Bailey2013}. 
State-of-the-art bioinformatic algorithms so-called peak finders (e.g., \cite{Laajala2009},\cite{Pepke2009},\cite{Wilbanks2010}), are used to detect transcription factor binding sites (TFBSs) in high-throughput chromatin immunoprecipitation followed by sequencing (ChIP-seq). The data analysis is usually based on peak-search criteria of the local maxima over enriched candidate regions. For purposes of computation several assumptions are made regarding the distribution of sample and control reads \cite{Bailey2013}. \\

Although most sites reported by peak finders could be narrowed down to 100-400bp using merely visual inspection, this reduction is not typically reflected by the regions provided by current methods, therefore degrading the resolution \cite{Rye2011}. It is widely accepted that the subdivision of long regions into distinct subpeaks can further help recognizing individual \emph{true} TFBSs that were merged into a wide area of signal enrichment (broad peak). \\

We present here the R package \Biocpkg{NarrowPeaks} \cite{MadrigalSubmitted} able process WIG format (one of the most popular formats for ChIP-seq data visualization is the \href{http://genome.ucsc.edu/FAQ/FAQformat}{wiggle track (WIG), and its indexed version bigWig}) data, and analyze it based on the theory of Functional Principal Component Analysis (FPCA) \cite{Ramsay2005}. Instructions to create WIG/bigWig coverage tracks can be found in \file{Text S1} in \cite{Bailey2013}  \\

The aim of this novel approach is to extract the most significant ChIP-seq enriched regions according to their primary modes of variation in the binding score profiles. It allows the user of this package to discriminate between binding regions in close proximity and shorten the length of the transcription factor binding sites preserving the information present in the the dataset at a desired level of variance.



\section{Methodolody}

The functional version of PCA establishes a method for estimating orthogonal basis functions (principal components or \emph{eigenfunctions}) from functional data \cite{Ramsay2005}, in order to capture as much of the variation as possible in as few components as possible. We can highlight the genomic locations contributing to maximum variation (measured by an aproximation of the variance-covariance function) from a list of peaks of a ChIP-seq experiment. \\

The proposed algorithm converts a continuous signal of enrichment (from a WIG file into CSAR binary format), and extracts signal profiles of candidate 
TFBSs. 
Afterwards, it characterizes the binding signals via spline basis functions expansion.
Finally, functional PCA is performed in order to measure the variation of the ChIP-seq signal profiles under study. The output consists of a score-ranked list of sites according to their contribution to the total variation, which is accounted for by the trimmed (narrowed) principal components (estimated from the data).


\section{Example}

We will use the example data set included in the \Biocpkg{NarrowPeaks} package for this demonstration. The data represents a small subset of a WIG file storing continuous value scores based on a Poisson test \cite{Muino2011} for the chromosome 1 of \emph{Arabidopsis thaliana} \cite{Kaufmann2010}. 

First, we load the \Biocpkg{NarrowPeaks} package and the data \Rclass{NarrowPeaks-dataset}, which contains a subsample of first 49515 lines of the original WIG file for the full experiment.
Using the function \Rfunction{wig2CSARScore} a set of binary files is constructed storing the enrichment-score profiles.

\begin{small}
<<write score binaries from a WIG file>>=  
library(NarrowPeaks)
data("NarrowPeaks-dataset")
head(wigfile_test)
writeLines(wigfile_test, con="wigfile.wig")
wigScores <- wig2CSARScore(wigfilename="wigfile.wig", nbchr = 1, chrle=c(30427671))
print(wigScores$infoscores$filenames)
@
\end{small}



Next, the candidate binding site regions are extracted using the Bioconductor package \Biocpkg{CSAR} \cite{Muino2011}. CSAR predictions are contiguous genomic regions separated by a maximum allowed of \Robject{g} base pairs, and score enrichment values greater than \Robject{t}. Candidate regions are stored in a \Robject{GRanges} object (see Bioconductor package \Biocpkg{GenomicRanges}). 
\textbf{Alternatively, ChIP-seq peaks obtained using other peak-callers can be provided building an analogous \Robject{GRanges} object}.

\begin{small}
<<extract candidate regions of enrichment in GRanges object>>=
library(CSAR)
candidates <- sigWin(experiment=wigScores$infoscores, t=1.0, g=30)
head(candidates)
@
\end{small}

If \Biocpkg{CSAR} \cite{Muino2011} is used first to analyze ChIP-seq data, from its results we can obtain the false discovery rate (FDR) for a given threshold. For example, for the complete experiment described in \cite{Kaufmann2010}, \Robject{t = 10.81} corresponds to FDR = 0.01 and \Robject{t = 6.78} corresponds to FDR = 0.1. \\

Now we want to narrow down the candidate sites with the function \Rfunction{narrowpeaks} to obtain shortened peaks , representing each candidate signal as a linear combination of \Robject{nbf} $B$-spline basis functions with no derivative penalization \cite{Ramsay2005} (\textbf{Figure 1}). We can specify the amount of miminum variance \Robject{pv} we want to describe in form of \Robject{npcomp} principal components, and establish a cutoff \Robject{pmaxscor} for trimming of scoring functions of the candidate sites \cite{MadrigalSubmitted}.

We will run the function for three different values of the cutoff: \Robject{pmaxscor = 0} (no cutoff), \Robject{pmaxscor = 3} (cutoff is at 3\% level of the maximum value relative to the scoring PCA functions) and  \Robject{pmaxscor = 100} (cutoff is at the maximum value relative to the scoring PCA functions).


\begin{small}
<<narrow down enriched regions by funtional PCA>>=
shortpeaksP0 <- narrowpeaks(inputReg=candidates, scoresInfo=wigScores$infoscores, lmin=0, nbf=25,
 rpenalty=0, nderiv=0, npcomp=2, pv=80, pmaxscor=0.0, ms=0)
head(shortpeaksP0$broadPeaks)
head(shortpeaksP0$narrowPeaks)
shortpeaksP3 <- narrowpeaks(inputReg=candidates, scoresInfo=wigScores$infoscores, lmin=0, nbf=25,
 rpenalty=0, nderiv=0, npcomp=2, pv=80, pmaxscor=3.0, ms=0)
head(shortpeaksP3$broadPeaks)
head(shortpeaksP3$narrowPeaks)
shortpeaksP100 <- narrowpeaks(inputReg=candidates, scoresInfo=wigScores$infoscores, lmin=0, nbf=25,
 rpenalty=0, nderiv=0, npcomp=2, pv=80, pmaxscor=100, ms=0)
head(shortpeaksP100$broadPeaks)
head(shortpeaksP100$narrowPeaks)
@
\end{small}



As we can see, there is no difference between \Robject{broadPeaks} and \Robject{narrowPeaks} for \Robject{pmaxscor = 0}, whereas for \Robject{pmaxscor = 100} just one punctual source of variation is reported. 
\textbf{Figure 2} shows the location narrowed regions for candidate peak 1 in the test data. 
The number of components (\Robject{reqcomp}) required, as well as the variance (\Robject{pvar}) achieved, are the same for all three cases (\Robject{pmaxscor} of 0, 3 and 100). 

\begin{small}
<<final number of components and variance>>=
print(shortpeaksP0$reqcomp)
print(shortpeaksP0$pvar)
@
\end{small}

Now, we can do the same for \Robject{pmaxscor = 90} and the result consists of 3 peaks very close to each other. We can tune the parameter \Robject{ms} to merge the sites into a unique peak:

\begin{small}
<<merge neighbouring narrow peaks>>=
shortpeaksP90 <- narrowpeaks(inputReg=candidates,scoresInfo=wigScores$infoscores, lmin=0, nbf=25,
 rpenalty=0, nderiv=0, npcomp=2, pv=80, pmaxscor=90, ms=0)
shortpeaksP90ms20 <- narrowpeaks(inputReg=candidates,scoresInfo=wigScores$infoscores, lmin=0, nbf=25,
 rpenalty=0,nderiv=0, npcomp=2, pv=80, pmaxscor=90, ms=20)
@
\end{small}
We can make use of the class \Rclass{GRangesLists} in the package \Biocpkg{GenomicRanges} to create a compound structure:

\begin{small}
<<create GRangesLists>>=
library(GenomicRanges)
exampleMerge <- GRangesList("narrowpeaksP90"=shortpeaksP90$narrowPeaks,
"narrowpeaksP90ms20"=shortpeaksP90ms20$narrowPeaks);
exampleMerge
@
\end{small}

Finally, we can export \Rclass{GRanges} objects or \Rclass{GRangesLists} into WIG, bedGraph, bigWig or other format files using the package \Biocpkg{rtracklayer}. For example:

\begin{small}
<<export GRanges to annotation tracks in various formats>>=
library(GenomicRanges)
names(elementMetadata(shortpeaksP3$broadPeaks))[3] <- "score"
names(elementMetadata(shortpeaksP3$narrowPeaks))[2] <- "score"
library(rtracklayer)
export.bedGraph(object=candidates, con="CSAR.bed")
export.bedGraph(object=shortpeaksP3$broadPeaks, con="broadPeaks.bed")
export.bedGraph(object=shortpeaksP3$narrowPeaks, con="narrowpeaks.bed")
@
\end{small}


\bibliography{NarrowPeaksVignette}{}
\bibliographystyle{plain}


\newpage

\section{Figures}

<<figureexample, fig=TRUE, include=TRUE, width=3.2, height=3.6, echo=FALSE, results=hide>>=
library(fda)
plot.fd(shortpeaksP0$fdaprofiles,xlab="nucleotides",cex.lab=0.5,cex.axis=0.5,cex.main=0.5, ylab="Read-enrichment profiles of candidate peaks", main="Figure 1")
@

%\newpage
%<<figureexample2, fig=TRUE, include=TRUE, width=2.2, height=2.6>>=
%library(fda)
%plot.fd(shortpeaksP0$fdaprofiles[1],cex.lab=0.5,cex.axis=0.5, xlab="Chr1", ylab="Read-enrichment profile of the candidate peak #1", main="Figure 2")
%@

\newpage
<<figureexample3, fig=TRUE, include=TRUE, width=3.2, height=3.6, echo=FALSE, results=hide>>=
library(fda)
dd=as.data.frame(candidates)
y=eval.fd(evalarg=1:(max(dd[,4])-1), fdobj=shortpeaksP0$fdaprofiles[1])
cent=round((19142+18996)/2)
plot((cent-round(max(dd[,4])/2)):round(cent+(max(dd[,4])/2)-1),y, type='l',cex.lab=0.5,cex.axis=0.5,cex.main=0.5,  xlab="Chr1", ylab="Read-enrichment profile of the candidate peak #1", main="Figure 2")
abline(v=18996, col="red")
abline(v=19142, col="red")
@


\section{Details}

This document was written using:

\begin{small}
<<sessionInfo>>=
sessionInfo()
@ 
\end{small}

\section{Funding}
This work was supported by the EU Marie Curie Initial Training Network SYSFLO (agreement number 237909).




\end{document}
