%\VignetteIndexEntry{NarrowPeaks Vignette II. Analysis of Variation for Differential Binding across ChIP-seq Samples.}
%\VignetteDepends{NarrowPeaks}
%\VignetteKeywords{Visualization,ChIPseq,Transcription,Genetics,Sequencing,HighThroughputSequencing}
%\VignettePackage{NarrowPeaks}
\documentclass{article}

<<style, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex()
@

\begin{document}

\title{\Rfunction{bigwigDiff}: Analysis of variation in differential binding across ChIP-seq samples}
\date{Created: January, 2013. Last modified: September, 2013. Compiled: \today}
\author{Pedro Madrigal}

\maketitle

\begin{small}
\begin{flushleft}
$^{1}$ Department of Biometry and Bioinformatics, Institute of Plant Genetics, Polish Academy of Sciences, Poznan, Poland \\
$^{2}$ \underline{Present address}: Wellcome Trust Sanger Institute, Hinxton, Cambridge, UK
\end{flushleft}
\end{small}

\tableofcontents

<<setup, echo=FALSE, results=hide>>=
options(width=60)
options(continue=" ")
options(prompt="R> ")
@ 

\section{Goal of this Vignette}
%I will show how to meaningfully split and narrow down the length a set of ChIP-seq peaks in a WIG file by means of PCA functional data analysis. 



\section{Introduction}
Under development.



\section{Details}

This document was written using:

\begin{small}
<<sessionInfo>>=
sessionInfo()
@ 
\end{small}

\section{Acknowledgements}
This work was supported by the EU Marie Curie Initial Training Network SYSFLO (agreement number 237909).

\end{document}


